### ISSUE TITLE
Mods that add a new gametype don't show up in webadmin

### ISSUE THREAD

**Issue by YodaDaCoda** [PhasecoreX/docker-ut2004-server#1]
Your install script adds addon `Paths` entries, but it also needs to add a `CacheRecordPath` entry for the addons.

e.g. my ini has

```
[Core.System]
...
CacheRecordPath=../System/*.ucl
CacheRecordPath=/data/addons/System/*.ucl
...
```

The second line is necessary e.g. for TeamArenaMaster show show up in the webadmin when added to addons instead of directly to server.

**Comment by PhasecoreX** [comment]
2c31cba should fix this. Thanks for reporting it!
