### ISSUE TITLE
MissingIni - Exiting due to error

### ISSUE THREAD

**Issue by cr4zymanz0r** [PhasecoreX/docker-ut2004-server#5]
When the game server (ucc-bin) attempts to run, it gives an error "MissingIni"
I verified the .ini symlinks were active in the docker image. I even created a non-symlinked copy in the /data/server/System folder and tried to run with it as the argument and it still gives a MissingIni error.

**Comment by PhasecoreX** [comment]
Can you supply your docker run command (or docker-compose.yml) with the cd key censored if present, as well as the logs?

**Comment by cr4zymanz0r** [comment]
I'm using Unraid which has uses a webui for setting up a docker image, but it does show the docker create command after saving it:

docker create --name='UT2k4-server' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e 'DOWNLOAD_DATA'='true' -e 'PUID'='1000' -e 'CD_KEY'='XXXXX-XXXXX-XXXXX-XXXXX' -e 'PGID'='1000' -p '7777:7777/udp' -v '/mnt/user/appdata/ut2k4-server':'/data':'rw' 'ghcr.io/phasecorex/ut2004-server:latest' 


After start it fresh this is the log output from the docker image:

Timezone set to America/Chicago
Starting with UID/GID: 1000/1000
Downloading ut2004server_base archive...
Verifying md5 checksum 561a9e3a5df492c2246c0be002eaf76e
ut2004server_base: OK
Extracting ut2004server_base archive...
Removing ut2004server_base archive
Starting server...
MissingIni
Exiting due to error


Any additional time I run it afterwards, it's basically just the same minus the initial download/extract steps:

Timezone set to America/Chicago
Starting with UID/GID: 1000/1000
Starting server...
MissingIni
Exiting due to error

**Comment by PhasecoreX** [comment]
My assumption is that it's an unraid volume issue. That '/mnt/user/appdata/ut2k4-server' folder isn't a network folder right?

Can you list the files inside of the /data/config folder, as well as confirm that there are files in the /data/server folder. I assume there are since the server is at least trying to start up.

**Comment by cr4zymanz0r** [comment]
"/data/server" has data
Here's all the files in "/data/config"
![image](https://user-images.githubusercontent.com/28268023/156899764-e7a40e24-83ec-41ac-b36e-b893484eca0f.png)

With Unraid essentially you can use a bunch of matched or mismatched HDDs to create an array. There's also the option for 1 or 2 parity drives (to lose 1 or 2 drives in the array without data loss) as long as the parity drive(s) are as large or larger as the biggest non-parity drive in the array.
There's also the option for a cache drive (stand alone or 2 for RAID-1). This cache drive is not part of the array, but can have shares created on it.
All of the data is local to the Unraid server, but you do create shares to access data over the network from other PCs and servers. the 'appdata' share is the default one to configure docker paths to. In my setup the 'appdata' share is on the cache drive (SSD) for better performance. This is a very common configuration in Unraid
All shares created in Unraid will be listed under "/mnt/user/".

So to Unraid, "/mnt/user/appdata/ut2k4-server" is the 'appdata' share on the cache drive.

As I troubleshooting step I forked your repo and added a 5 minute sleep right before it tries to start the UT2004 server so I could run a terminal within the docker image while it's running to validate things appear to be correct. I could 'ls' in "/data/server/System" and see the ini files were present as symlinks and while in the folder could do other commands against them successfully such as "cat UT2004.ini".
I tried running "./ucc-bin server DM-Antalus?game=xGame.xDeathMatch ini=UT2004.ini -nohomedir" myself from the terminal and it still complained about MissingIni. I created a copy of UT2004.ini directly in "/data/server/System" (not a symlink) and tried that as the argument and got the same MissingIni error. I tried removing the ini argument complete and still got the same error.

It's just a really weird issue that almost seems more like ucc-bin has a bug since nothing else is logically making sense to me

**Comment by PhasecoreX** [comment]
The only difference I can see between yours and mine is that you are missing a `User.ini` file. Usually when that's missing, the ucc-bin will copy the `Default.ini` over to `User.ini`. Just tested it with mine, deleted the `User.ini` file, stopped and removed the container, and started it.

Now, I am not sure if this copying is just not working for some reason in unraid and ucc-bin is indeed expecting this file. Or maybe it is working and you just didn't restart the server a second time for the docker image to copy and symlink the new files. Regardless, try copying `Default.ini` to a new file `User.ini` in the config folder. Not sure if it will help anything.

It would be helpful if the "MissingIni" message actually told us what ini was missing...

**Comment by cr4zymanz0r** [comment]
I can start the server multiple times and it never creates the User.ini
I tried your suggestion of copying Default.ini to a new User.ini file and tried starting the server multiple times but still only geting "MissingIni" 
¯\_(ツ)_/¯

**Comment by PhasecoreX** [comment]
Yeah I can't reproduce this... Maybe it is some Unraid thing. My Docker just runs on a server with direct access to the disk itself. There isn't any abstraction between it and cache drives, for example. I don't have Unraid so I can't test it for myself. More ideas came to mind though, so more questions.

Does the cache SSD that `/mnt/user/appdata/ut2k4-server` is pointing at have permissions? As in, what file system is it? Ext4?

With your delay 5 minutes fork, when you look into the `/data/config` and /data/server/System` folders, do the *.ini files have proper read permissions and are owned by the user 1000 (in your case)? Doing `ls -la *.ini` should show this information. Maybe also check the `cdkey` file as well in these folders.

I'm scraping the bottom of the barrel here lol.

**Comment by cr4zymanz0r** [comment]
The cache drive uses BRTFS, and the regular array drives are XFS. (I believe these are the defaults for Unraid, but can be set to something different when setting up the drives).

Here's the information/permissions for the "/data/config" folder:
![image](https://user-images.githubusercontent.com/28268023/158908471-37c8d4bb-589e-4e9e-b4f6-17124690a646.png)

Here's the "/data/server/System" folder:
![image](https://user-images.githubusercontent.com/28268023/158909421-c70ef715-6199-4232-87fe-e1ed32ad70c5.png)

I'll admit my knowledge of Linux permissions isn't fantastic, so if there's a glaring issue with that I might now know :P

You got me thinking though. I changed the path mapping to (supposedly) go directly to one of the array disks (/mnt/disk1/downloads/ut2k4test), and now I get a different error:

Starting server...
=======================================
ucc.exe: UnrealOS execution environment
Copyright 2001 Epic Games Inc
=======================================

Commandlet server not found

**Comment by cr4zymanz0r** [comment]
aaaand I made it work ¯\\_(ツ)\_/¯
swapped the path back to "/mnt/user/appdata/ut2k4-server" and confirmed I still got the original MissingIni error. I then changed the path to (supposedly) directly go to the cache drive, "/mnt/cache/appdata/ut2k4-server/" instead of using the Unraid fileshare mappings then it worked.

That's really weird. Docker images in the Unraid community apps nearly always use "/mnt/user/appdata/<app_folder>" in their template as the path and have no issues. The purpose seems to be when assigning the path that way if you have no cache drive or (properly) get rid of your cache drive then that appdata share will still be accessible, but it'll just be on the regular array drive(s). If it's pointed to "/mnt/cache/appdata/<whatever>", then if the cache drive no longer exists then all the docker images trying to map there would fail to run until their mapping were changed to "/mnt/user/appdata/<whatever>" or a cache drive was (re)added.

Here's the information/permissions on the folders within the docker container when using "/mnt/cache/appdata/ut2k4-server/":
![image](https://user-images.githubusercontent.com/28268023/158912597-d59b65b2-a8ab-4995-adce-5d032ec5194e.png)

![image](https://user-images.githubusercontent.com/28268023/158912684-920de8b9-e138-4a80-a97f-8fd70c0c3011.png)

Don't know if that will clue in what the precise problem was or not.
Afterwards for good measure I completely deleted the ut2k4-server folder to let it start fresh with the new path and it still worked correctly.

You can close the issue now, but I'd be interested to hear what the reason was it failed with the original (if that's easily discernible from the data).
